name: Ro11enWar
version: '${project.version}'
main: com.somemone.ro11enwar.Ro11enWar
api-version: 1.18
authors: [ Somemone ]
depend: [Towny, FlagWar]
description: New Features for wars on the Ro11en server

commands:
  war:
    usage: /war <nation>
    description: Declares war on another country

permissions:
  ro11ensmpcore.waradmin:
    description: Allows player to skip wait for declaring war
    default: op