name: Ro11enSMPCore
version: '${project.version}'
main: com.somemone.ro11ensmpcore.Ro11enSmpCore
api-version: 1.18
authors: [ Somemone ]
depend: [Towny, FlagWar]
description: Minceraft gaming time :)))

commands:
  ro11ensettings:
    usage: /ro11ensettings
    description: jkjkjkjk

  war:
    usage: /war <nation>
    description: Declares war on another country

permissions:
  ro11ensmpcore.waradmin:
    description: Allows player to skip wait for declaring war
    default: op