name: Ro11enSMPCore
version: '${project.version}'
main: com.somemone.ro11ensmpcore.Ro11enSmpCore
api-version: 1.18
authors: [ Somemone ]
description: Minceraft gaming time :)))

commands:
  ro11ensettings:
    usage: /ro11ensettings
    description: jkjkjkjk

  war:
    usage: /war <nation>
    description: Declares war on another country